/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getVehicleAccess().getAlternatives(), "rule__Vehicle__Alternatives");
			builder.put(grammarAccess.getAmmunitionAccess().getAlternatives(), "rule__Ammunition__Alternatives");
			builder.put(grammarAccess.getDroneAccess().getAlternatives(), "rule__Drone__Alternatives");
			builder.put(grammarAccess.getCarrierAircraftAccess().getAlternatives(), "rule__CarrierAircraft__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getResourcesAccess().getGroup(), "rule__Resources__Group__0");
			builder.put(grammarAccess.getResourcesAccess().getGroup_4(), "rule__Resources__Group_4__0");
			builder.put(grammarAccess.getResourcesAccess().getGroup_4_3(), "rule__Resources__Group_4_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getFrigateAccess().getGroup(), "rule__Frigate__Group__0");
			builder.put(grammarAccess.getFrigateAccess().getGroup_4(), "rule__Frigate__Group_4__0");
			builder.put(grammarAccess.getFrigateAccess().getGroup_5(), "rule__Frigate__Group_5__0");
			builder.put(grammarAccess.getFrigateAccess().getGroup_5_3(), "rule__Frigate__Group_5_3__0");
			builder.put(grammarAccess.getFrigateAccess().getGroup_6(), "rule__Frigate__Group_6__0");
			builder.put(grammarAccess.getFrigateAccess().getGroup_6_3(), "rule__Frigate__Group_6_3__0");
			builder.put(grammarAccess.getFrigateAccess().getGroup_7(), "rule__Frigate__Group_7__0");
			builder.put(grammarAccess.getFrigateAccess().getGroup_7_3(), "rule__Frigate__Group_7_3__0");
			builder.put(grammarAccess.getDestroyerAccess().getGroup(), "rule__Destroyer__Group__0");
			builder.put(grammarAccess.getDestroyerAccess().getGroup_4(), "rule__Destroyer__Group_4__0");
			builder.put(grammarAccess.getDestroyerAccess().getGroup_5(), "rule__Destroyer__Group_5__0");
			builder.put(grammarAccess.getDestroyerAccess().getGroup_5_3(), "rule__Destroyer__Group_5_3__0");
			builder.put(grammarAccess.getDestroyerAccess().getGroup_6(), "rule__Destroyer__Group_6__0");
			builder.put(grammarAccess.getDestroyerAccess().getGroup_6_3(), "rule__Destroyer__Group_6_3__0");
			builder.put(grammarAccess.getDestroyerAccess().getGroup_7(), "rule__Destroyer__Group_7__0");
			builder.put(grammarAccess.getDestroyerAccess().getGroup_7_3(), "rule__Destroyer__Group_7_3__0");
			builder.put(grammarAccess.getAircraftCarrierAccess().getGroup(), "rule__AircraftCarrier__Group__0");
			builder.put(grammarAccess.getAircraftCarrierAccess().getGroup_4(), "rule__AircraftCarrier__Group_4__0");
			builder.put(grammarAccess.getAircraftCarrierAccess().getGroup_5(), "rule__AircraftCarrier__Group_5__0");
			builder.put(grammarAccess.getAircraftCarrierAccess().getGroup_5_3(), "rule__AircraftCarrier__Group_5_3__0");
			builder.put(grammarAccess.getAircraftCarrierAccess().getGroup_6(), "rule__AircraftCarrier__Group_6__0");
			builder.put(grammarAccess.getAircraftCarrierAccess().getGroup_6_3(), "rule__AircraftCarrier__Group_6_3__0");
			builder.put(grammarAccess.getAircraftCarrierAccess().getGroup_7(), "rule__AircraftCarrier__Group_7__0");
			builder.put(grammarAccess.getAircraftCarrierAccess().getGroup_7_3(), "rule__AircraftCarrier__Group_7_3__0");
			builder.put(grammarAccess.getReconnaissanceAccess().getGroup(), "rule__Reconnaissance__Group__0");
			builder.put(grammarAccess.getReconnaissanceAccess().getGroup_4(), "rule__Reconnaissance__Group_4__0");
			builder.put(grammarAccess.getReconnaissanceAccess().getGroup_5(), "rule__Reconnaissance__Group_5__0");
			builder.put(grammarAccess.getReconnaissanceAccess().getGroup_5_3(), "rule__Reconnaissance__Group_5_3__0");
			builder.put(grammarAccess.getStrikeAccess().getGroup(), "rule__Strike__Group__0");
			builder.put(grammarAccess.getStrikeAccess().getGroup_4(), "rule__Strike__Group_4__0");
			builder.put(grammarAccess.getStrikeAccess().getGroup_5(), "rule__Strike__Group_5__0");
			builder.put(grammarAccess.getStrikeAccess().getGroup_5_3(), "rule__Strike__Group_5_3__0");
			builder.put(grammarAccess.getTransportAccess().getGroup(), "rule__Transport__Group__0");
			builder.put(grammarAccess.getTransportAccess().getGroup_4(), "rule__Transport__Group_4__0");
			builder.put(grammarAccess.getTransportAccess().getGroup_5(), "rule__Transport__Group_5__0");
			builder.put(grammarAccess.getTransportAccess().getGroup_5_3(), "rule__Transport__Group_5_3__0");
			builder.put(grammarAccess.getFighterAccess().getGroup(), "rule__Fighter__Group__0");
			builder.put(grammarAccess.getFighterAccess().getGroup_4(), "rule__Fighter__Group_4__0");
			builder.put(grammarAccess.getFighterAccess().getGroup_5(), "rule__Fighter__Group_5__0");
			builder.put(grammarAccess.getFighterAccess().getGroup_5_3(), "rule__Fighter__Group_5_3__0");
			builder.put(grammarAccess.getReconAccess().getGroup(), "rule__Recon__Group__0");
			builder.put(grammarAccess.getReconAccess().getGroup_4(), "rule__Recon__Group_4__0");
			builder.put(grammarAccess.getReconAccess().getGroup_5(), "rule__Recon__Group_5__0");
			builder.put(grammarAccess.getReconAccess().getGroup_5_3(), "rule__Recon__Group_5_3__0");
			builder.put(grammarAccess.getHelicopterAccess().getGroup(), "rule__Helicopter__Group__0");
			builder.put(grammarAccess.getHelicopterAccess().getGroup_4(), "rule__Helicopter__Group_4__0");
			builder.put(grammarAccess.getHelicopterAccess().getGroup_5(), "rule__Helicopter__Group_5__0");
			builder.put(grammarAccess.getHelicopterAccess().getGroup_5_3(), "rule__Helicopter__Group_5_3__0");
			builder.put(grammarAccess.getMissileAccess().getGroup(), "rule__Missile__Group__0");
			builder.put(grammarAccess.getMissileAccess().getGroup_4(), "rule__Missile__Group_4__0");
			builder.put(grammarAccess.getShellAccess().getGroup(), "rule__Shell__Group__0");
			builder.put(grammarAccess.getShellAccess().getGroup_4(), "rule__Shell__Group_4__0");
			builder.put(grammarAccess.getTorpedoAccess().getGroup(), "rule__Torpedo__Group__0");
			builder.put(grammarAccess.getTorpedoAccess().getGroup_4(), "rule__Torpedo__Group_4__0");
			builder.put(grammarAccess.getResourcesAccess().getNameAssignment_2(), "rule__Resources__NameAssignment_2");
			builder.put(grammarAccess.getResourcesAccess().getVehiclesAssignment_4_2(), "rule__Resources__VehiclesAssignment_4_2");
			builder.put(grammarAccess.getResourcesAccess().getVehiclesAssignment_4_3_1(), "rule__Resources__VehiclesAssignment_4_3_1");
			builder.put(grammarAccess.getFrigateAccess().getNameAssignment_2(), "rule__Frigate__NameAssignment_2");
			builder.put(grammarAccess.getFrigateAccess().getAmountAssignment_4_1(), "rule__Frigate__AmountAssignment_4_1");
			builder.put(grammarAccess.getFrigateAccess().getDroneAssignment_5_2(), "rule__Frigate__DroneAssignment_5_2");
			builder.put(grammarAccess.getFrigateAccess().getDroneAssignment_5_3_1(), "rule__Frigate__DroneAssignment_5_3_1");
			builder.put(grammarAccess.getFrigateAccess().getHelicopterAssignment_6_2(), "rule__Frigate__HelicopterAssignment_6_2");
			builder.put(grammarAccess.getFrigateAccess().getHelicopterAssignment_6_3_1(), "rule__Frigate__HelicopterAssignment_6_3_1");
			builder.put(grammarAccess.getFrigateAccess().getAmmunitionsAssignment_7_2(), "rule__Frigate__AmmunitionsAssignment_7_2");
			builder.put(grammarAccess.getFrigateAccess().getAmmunitionsAssignment_7_3_1(), "rule__Frigate__AmmunitionsAssignment_7_3_1");
			builder.put(grammarAccess.getDestroyerAccess().getNameAssignment_2(), "rule__Destroyer__NameAssignment_2");
			builder.put(grammarAccess.getDestroyerAccess().getAmountAssignment_4_1(), "rule__Destroyer__AmountAssignment_4_1");
			builder.put(grammarAccess.getDestroyerAccess().getDroneAssignment_5_2(), "rule__Destroyer__DroneAssignment_5_2");
			builder.put(grammarAccess.getDestroyerAccess().getDroneAssignment_5_3_1(), "rule__Destroyer__DroneAssignment_5_3_1");
			builder.put(grammarAccess.getDestroyerAccess().getHelicopterAssignment_6_2(), "rule__Destroyer__HelicopterAssignment_6_2");
			builder.put(grammarAccess.getDestroyerAccess().getHelicopterAssignment_6_3_1(), "rule__Destroyer__HelicopterAssignment_6_3_1");
			builder.put(grammarAccess.getDestroyerAccess().getAmmunitionsAssignment_7_2(), "rule__Destroyer__AmmunitionsAssignment_7_2");
			builder.put(grammarAccess.getDestroyerAccess().getAmmunitionsAssignment_7_3_1(), "rule__Destroyer__AmmunitionsAssignment_7_3_1");
			builder.put(grammarAccess.getAircraftCarrierAccess().getNameAssignment_2(), "rule__AircraftCarrier__NameAssignment_2");
			builder.put(grammarAccess.getAircraftCarrierAccess().getAmountAssignment_4_1(), "rule__AircraftCarrier__AmountAssignment_4_1");
			builder.put(grammarAccess.getAircraftCarrierAccess().getDroneAssignment_5_2(), "rule__AircraftCarrier__DroneAssignment_5_2");
			builder.put(grammarAccess.getAircraftCarrierAccess().getDroneAssignment_5_3_1(), "rule__AircraftCarrier__DroneAssignment_5_3_1");
			builder.put(grammarAccess.getAircraftCarrierAccess().getCarrieraircraftAssignment_6_2(), "rule__AircraftCarrier__CarrieraircraftAssignment_6_2");
			builder.put(grammarAccess.getAircraftCarrierAccess().getCarrieraircraftAssignment_6_3_1(), "rule__AircraftCarrier__CarrieraircraftAssignment_6_3_1");
			builder.put(grammarAccess.getAircraftCarrierAccess().getAmmunitionsAssignment_7_2(), "rule__AircraftCarrier__AmmunitionsAssignment_7_2");
			builder.put(grammarAccess.getAircraftCarrierAccess().getAmmunitionsAssignment_7_3_1(), "rule__AircraftCarrier__AmmunitionsAssignment_7_3_1");
			builder.put(grammarAccess.getReconnaissanceAccess().getNameAssignment_2(), "rule__Reconnaissance__NameAssignment_2");
			builder.put(grammarAccess.getReconnaissanceAccess().getAmountAssignment_4_1(), "rule__Reconnaissance__AmountAssignment_4_1");
			builder.put(grammarAccess.getReconnaissanceAccess().getAmmunitionsAssignment_5_2(), "rule__Reconnaissance__AmmunitionsAssignment_5_2");
			builder.put(grammarAccess.getReconnaissanceAccess().getAmmunitionsAssignment_5_3_1(), "rule__Reconnaissance__AmmunitionsAssignment_5_3_1");
			builder.put(grammarAccess.getStrikeAccess().getNameAssignment_2(), "rule__Strike__NameAssignment_2");
			builder.put(grammarAccess.getStrikeAccess().getAmountAssignment_4_1(), "rule__Strike__AmountAssignment_4_1");
			builder.put(grammarAccess.getStrikeAccess().getAmmunitionsAssignment_5_2(), "rule__Strike__AmmunitionsAssignment_5_2");
			builder.put(grammarAccess.getStrikeAccess().getAmmunitionsAssignment_5_3_1(), "rule__Strike__AmmunitionsAssignment_5_3_1");
			builder.put(grammarAccess.getTransportAccess().getNameAssignment_2(), "rule__Transport__NameAssignment_2");
			builder.put(grammarAccess.getTransportAccess().getAmountAssignment_4_1(), "rule__Transport__AmountAssignment_4_1");
			builder.put(grammarAccess.getTransportAccess().getAmmunitionsAssignment_5_2(), "rule__Transport__AmmunitionsAssignment_5_2");
			builder.put(grammarAccess.getTransportAccess().getAmmunitionsAssignment_5_3_1(), "rule__Transport__AmmunitionsAssignment_5_3_1");
			builder.put(grammarAccess.getFighterAccess().getNameAssignment_2(), "rule__Fighter__NameAssignment_2");
			builder.put(grammarAccess.getFighterAccess().getAmountAssignment_4_1(), "rule__Fighter__AmountAssignment_4_1");
			builder.put(grammarAccess.getFighterAccess().getAmmunitionsAssignment_5_2(), "rule__Fighter__AmmunitionsAssignment_5_2");
			builder.put(grammarAccess.getFighterAccess().getAmmunitionsAssignment_5_3_1(), "rule__Fighter__AmmunitionsAssignment_5_3_1");
			builder.put(grammarAccess.getReconAccess().getNameAssignment_2(), "rule__Recon__NameAssignment_2");
			builder.put(grammarAccess.getReconAccess().getAmountAssignment_4_1(), "rule__Recon__AmountAssignment_4_1");
			builder.put(grammarAccess.getReconAccess().getAmmunitionsAssignment_5_2(), "rule__Recon__AmmunitionsAssignment_5_2");
			builder.put(grammarAccess.getReconAccess().getAmmunitionsAssignment_5_3_1(), "rule__Recon__AmmunitionsAssignment_5_3_1");
			builder.put(grammarAccess.getHelicopterAccess().getNameAssignment_2(), "rule__Helicopter__NameAssignment_2");
			builder.put(grammarAccess.getHelicopterAccess().getAmountAssignment_4_1(), "rule__Helicopter__AmountAssignment_4_1");
			builder.put(grammarAccess.getHelicopterAccess().getAmmunitionsAssignment_5_2(), "rule__Helicopter__AmmunitionsAssignment_5_2");
			builder.put(grammarAccess.getHelicopterAccess().getAmmunitionsAssignment_5_3_1(), "rule__Helicopter__AmmunitionsAssignment_5_3_1");
			builder.put(grammarAccess.getMissileAccess().getNameAssignment_2(), "rule__Missile__NameAssignment_2");
			builder.put(grammarAccess.getMissileAccess().getAmountAssignment_4_1(), "rule__Missile__AmountAssignment_4_1");
			builder.put(grammarAccess.getShellAccess().getNameAssignment_2(), "rule__Shell__NameAssignment_2");
			builder.put(grammarAccess.getShellAccess().getAmountAssignment_4_1(), "rule__Shell__AmountAssignment_4_1");
			builder.put(grammarAccess.getTorpedoAccess().getNameAssignment_2(), "rule__Torpedo__NameAssignment_2");
			builder.put(grammarAccess.getTorpedoAccess().getAmountAssignment_4_1(), "rule__Torpedo__AmountAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
