<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="resources" nsURI="http://www.example.org/resources" nsPrefix="resources">
  <eClassifiers xsi:type="ecore:EClass" name="Resources">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicles" upperBound="-1"
        eType="#//Vehicle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ship" abstract="true" eSuperTypes="#//Vehicle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ammunition" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Drone" abstract="true" eSuperTypes="#//Vehicle"/>
  <eClassifiers xsi:type="ecore:EClass" name="CarrierAircraft" abstract="true" eSuperTypes="#//Vehicle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Frigate" eSuperTypes="#//Ship"/>
  <eClassifiers xsi:type="ecore:EClass" name="Destroyer" eSuperTypes="#//Ship"/>
  <eClassifiers xsi:type="ecore:EClass" name="AircraftCarrier" eSuperTypes="#//Ship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="carrieraircrafts" upperBound="-1"
        eType="#//CarrierAircraft" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Missile" eSuperTypes="#//Ammunition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//Status"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shell" eSuperTypes="#//Ammunition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Torpedo" eSuperTypes="#//Ammunition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reconnaissance" eSuperTypes="#//Drone"/>
  <eClassifiers xsi:type="ecore:EClass" name="Strike" eSuperTypes="#//Drone"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transport" eSuperTypes="#//Drone"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fighter" eSuperTypes="#//CarrierAircraft"/>
  <eClassifiers xsi:type="ecore:EClass" name="Recon" eSuperTypes="#//CarrierAircraft"/>
  <eClassifiers xsi:type="ecore:EClass" name="Helicopter" eSuperTypes="#//CarrierAircraft"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Status">
    <eLiterals name="fdj"/>
    <eLiterals name="phy" value="1"/>
    <eLiterals name="gee" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ammunitions" upperBound="-1"
        eType="#//Ammunition" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
