/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ResourcesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Resources");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cResourcesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cResourcesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVehiclesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cVehiclesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cVehiclesVehicleParserRuleCall_4_2_0 = (RuleCall)cVehiclesAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cVehiclesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cVehiclesVehicleParserRuleCall_4_3_1_0 = (RuleCall)cVehiclesAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Resources returns Resources:
		//    {Resources}
		//    'Resources'
		//    name=EString
		//    '{'
		//        ('vehicles' '{' vehicles+=Vehicle ( "," vehicles+=Vehicle)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Resources}
		//'Resources'
		//name=EString
		//'{'
		//    ('vehicles' '{' vehicles+=Vehicle ( "," vehicles+=Vehicle)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Resources}
		public Action getResourcesAction_0() { return cResourcesAction_0; }
		
		//'Resources'
		public Keyword getResourcesKeyword_1() { return cResourcesKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('vehicles' '{' vehicles+=Vehicle ( "," vehicles+=Vehicle)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'vehicles'
		public Keyword getVehiclesKeyword_4_0() { return cVehiclesKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//vehicles+=Vehicle
		public Assignment getVehiclesAssignment_4_2() { return cVehiclesAssignment_4_2; }
		
		//Vehicle
		public RuleCall getVehiclesVehicleParserRuleCall_4_2_0() { return cVehiclesVehicleParserRuleCall_4_2_0; }
		
		//( "," vehicles+=Vehicle)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//vehicles+=Vehicle
		public Assignment getVehiclesAssignment_4_3_1() { return cVehiclesAssignment_4_3_1; }
		
		//Vehicle
		public RuleCall getVehiclesVehicleParserRuleCall_4_3_1_0() { return cVehiclesVehicleParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class VehicleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Vehicle");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFrigateParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDestroyerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAircraftCarrierParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cReconnaissanceParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cStrikeParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cTransportParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cFighterParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cReconParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cHelicopterParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		
		//Vehicle returns Vehicle:
		//    Frigate | Destroyer | AircraftCarrier | Reconnaissance | Strike | Transport | Fighter | Recon | Helicopter;
		@Override public ParserRule getRule() { return rule; }
		
		//Frigate | Destroyer | AircraftCarrier | Reconnaissance | Strike | Transport | Fighter | Recon | Helicopter
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Frigate
		public RuleCall getFrigateParserRuleCall_0() { return cFrigateParserRuleCall_0; }
		
		//Destroyer
		public RuleCall getDestroyerParserRuleCall_1() { return cDestroyerParserRuleCall_1; }
		
		//AircraftCarrier
		public RuleCall getAircraftCarrierParserRuleCall_2() { return cAircraftCarrierParserRuleCall_2; }
		
		//Reconnaissance
		public RuleCall getReconnaissanceParserRuleCall_3() { return cReconnaissanceParserRuleCall_3; }
		
		//Strike
		public RuleCall getStrikeParserRuleCall_4() { return cStrikeParserRuleCall_4; }
		
		//Transport
		public RuleCall getTransportParserRuleCall_5() { return cTransportParserRuleCall_5; }
		
		//Fighter
		public RuleCall getFighterParserRuleCall_6() { return cFighterParserRuleCall_6; }
		
		//Recon
		public RuleCall getReconParserRuleCall_7() { return cReconParserRuleCall_7; }
		
		//Helicopter
		public RuleCall getHelicopterParserRuleCall_8() { return cHelicopterParserRuleCall_8; }
	}
	public class AmmunitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Ammunition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMissileParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cShellParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTorpedoParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Ammunition returns Ammunition:
		//    Missile | Shell | Torpedo;
		@Override public ParserRule getRule() { return rule; }
		
		//Missile | Shell | Torpedo
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Missile
		public RuleCall getMissileParserRuleCall_0() { return cMissileParserRuleCall_0; }
		
		//Shell
		public RuleCall getShellParserRuleCall_1() { return cShellParserRuleCall_1; }
		
		//Torpedo
		public RuleCall getTorpedoParserRuleCall_2() { return cTorpedoParserRuleCall_2; }
	}
	public class DroneElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Drone");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cReconnaissanceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStrikeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTransportParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Drone returns Drone:
		//    Reconnaissance | Strike | Transport;
		@Override public ParserRule getRule() { return rule; }
		
		//Reconnaissance | Strike | Transport
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Reconnaissance
		public RuleCall getReconnaissanceParserRuleCall_0() { return cReconnaissanceParserRuleCall_0; }
		
		//Strike
		public RuleCall getStrikeParserRuleCall_1() { return cStrikeParserRuleCall_1; }
		
		//Transport
		public RuleCall getTransportParserRuleCall_2() { return cTransportParserRuleCall_2; }
	}
	public class CarrierAircraftElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.CarrierAircraft");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFighterParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cReconParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cHelicopterParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//CarrierAircraft returns CarrierAircraft:
		//    Fighter | Recon | Helicopter;
		@Override public ParserRule getRule() { return rule; }
		
		//Fighter | Recon | Helicopter
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Fighter
		public RuleCall getFighterParserRuleCall_0() { return cFighterParserRuleCall_0; }
		
		//Recon
		public RuleCall getReconParserRuleCall_1() { return cReconParserRuleCall_1; }
		
		//Helicopter
		public RuleCall getHelicopterParserRuleCall_2() { return cHelicopterParserRuleCall_2; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class FrigateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Frigate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFrigateAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFrigateKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAmountKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAmountAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAmountEIntParserRuleCall_4_1_0 = (RuleCall)cAmountAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDroneKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cDroneAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cDroneDroneCrossReference_5_2_0 = (CrossReference)cDroneAssignment_5_2.eContents().get(0);
		private final RuleCall cDroneDroneEStringParserRuleCall_5_2_0_1 = (RuleCall)cDroneDroneCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cDroneAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cDroneDroneCrossReference_5_3_1_0 = (CrossReference)cDroneAssignment_5_3_1.eContents().get(0);
		private final RuleCall cDroneDroneEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cDroneDroneCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cHelicopterKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cHelicopterAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cHelicopterHelicopterCrossReference_6_2_0 = (CrossReference)cHelicopterAssignment_6_2.eContents().get(0);
		private final RuleCall cHelicopterHelicopterEStringParserRuleCall_6_2_0_1 = (RuleCall)cHelicopterHelicopterCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cHelicopterAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cHelicopterHelicopterCrossReference_6_3_1_0 = (CrossReference)cHelicopterAssignment_6_3_1.eContents().get(0);
		private final RuleCall cHelicopterHelicopterEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cHelicopterHelicopterCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAmmunitionsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cAmmunitionsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_7_2_0 = (RuleCall)cAmmunitionsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cAmmunitionsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_7_3_1_0 = (RuleCall)cAmmunitionsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Frigate returns Frigate:
		//    {Frigate}
		//    'Frigate'
		//    name=EString
		//    '{'
		//        ('amount' amount=EInt)?
		//        ('drone' '(' drone+=[Drone|EString] ( "," drone+=[Drone|EString])* ')' )?
		//        ('helicopter' '(' helicopter+=[Helicopter|EString] ( "," helicopter+=[Helicopter|EString])* ')' )?
		//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Frigate}
		//'Frigate'
		//name=EString
		//'{'
		//    ('amount' amount=EInt)?
		//    ('drone' '(' drone+=[Drone|EString] ( "," drone+=[Drone|EString])* ')' )?
		//    ('helicopter' '(' helicopter+=[Helicopter|EString] ( "," helicopter+=[Helicopter|EString])* ')' )?
		//    ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Frigate}
		public Action getFrigateAction_0() { return cFrigateAction_0; }
		
		//'Frigate'
		public Keyword getFrigateKeyword_1() { return cFrigateKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('amount' amount=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'amount'
		public Keyword getAmountKeyword_4_0() { return cAmountKeyword_4_0; }
		
		//amount=EInt
		public Assignment getAmountAssignment_4_1() { return cAmountAssignment_4_1; }
		
		//EInt
		public RuleCall getAmountEIntParserRuleCall_4_1_0() { return cAmountEIntParserRuleCall_4_1_0; }
		
		//('drone' '(' drone+=[Drone|EString] ( "," drone+=[Drone|EString])* ')' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'drone'
		public Keyword getDroneKeyword_5_0() { return cDroneKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//drone+=[Drone|EString]
		public Assignment getDroneAssignment_5_2() { return cDroneAssignment_5_2; }
		
		//[Drone|EString]
		public CrossReference getDroneDroneCrossReference_5_2_0() { return cDroneDroneCrossReference_5_2_0; }
		
		//EString
		public RuleCall getDroneDroneEStringParserRuleCall_5_2_0_1() { return cDroneDroneEStringParserRuleCall_5_2_0_1; }
		
		//( "," drone+=[Drone|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//drone+=[Drone|EString]
		public Assignment getDroneAssignment_5_3_1() { return cDroneAssignment_5_3_1; }
		
		//[Drone|EString]
		public CrossReference getDroneDroneCrossReference_5_3_1_0() { return cDroneDroneCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getDroneDroneEStringParserRuleCall_5_3_1_0_1() { return cDroneDroneEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('helicopter' '(' helicopter+=[Helicopter|EString] ( "," helicopter+=[Helicopter|EString])* ')' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'helicopter'
		public Keyword getHelicopterKeyword_6_0() { return cHelicopterKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//helicopter+=[Helicopter|EString]
		public Assignment getHelicopterAssignment_6_2() { return cHelicopterAssignment_6_2; }
		
		//[Helicopter|EString]
		public CrossReference getHelicopterHelicopterCrossReference_6_2_0() { return cHelicopterHelicopterCrossReference_6_2_0; }
		
		//EString
		public RuleCall getHelicopterHelicopterEStringParserRuleCall_6_2_0_1() { return cHelicopterHelicopterEStringParserRuleCall_6_2_0_1; }
		
		//( "," helicopter+=[Helicopter|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//helicopter+=[Helicopter|EString]
		public Assignment getHelicopterAssignment_6_3_1() { return cHelicopterAssignment_6_3_1; }
		
		//[Helicopter|EString]
		public CrossReference getHelicopterHelicopterCrossReference_6_3_1_0() { return cHelicopterHelicopterCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getHelicopterHelicopterEStringParserRuleCall_6_3_1_0_1() { return cHelicopterHelicopterEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'ammunitions'
		public Keyword getAmmunitionsKeyword_7_0() { return cAmmunitionsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_7_2() { return cAmmunitionsAssignment_7_2; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_7_2_0() { return cAmmunitionsAmmunitionParserRuleCall_7_2_0; }
		
		//( "," ammunitions+=Ammunition)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_7_3_1() { return cAmmunitionsAssignment_7_3_1; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_7_3_1_0() { return cAmmunitionsAmmunitionParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class DestroyerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Destroyer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDestroyerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDestroyerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAmountKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAmountAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAmountEIntParserRuleCall_4_1_0 = (RuleCall)cAmountAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDroneKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cDroneAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cDroneDroneCrossReference_5_2_0 = (CrossReference)cDroneAssignment_5_2.eContents().get(0);
		private final RuleCall cDroneDroneEStringParserRuleCall_5_2_0_1 = (RuleCall)cDroneDroneCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cDroneAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cDroneDroneCrossReference_5_3_1_0 = (CrossReference)cDroneAssignment_5_3_1.eContents().get(0);
		private final RuleCall cDroneDroneEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cDroneDroneCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cHelicopterKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cHelicopterAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cHelicopterHelicopterCrossReference_6_2_0 = (CrossReference)cHelicopterAssignment_6_2.eContents().get(0);
		private final RuleCall cHelicopterHelicopterEStringParserRuleCall_6_2_0_1 = (RuleCall)cHelicopterHelicopterCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cHelicopterAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cHelicopterHelicopterCrossReference_6_3_1_0 = (CrossReference)cHelicopterAssignment_6_3_1.eContents().get(0);
		private final RuleCall cHelicopterHelicopterEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cHelicopterHelicopterCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAmmunitionsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cAmmunitionsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_7_2_0 = (RuleCall)cAmmunitionsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cAmmunitionsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_7_3_1_0 = (RuleCall)cAmmunitionsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Destroyer returns Destroyer:
		//    {Destroyer}
		//    'Destroyer'
		//    name=EString
		//    '{'
		//        ('amount' amount=EInt)?
		//        ('drone' '(' drone+=[Drone|EString] ( "," drone+=[Drone|EString])* ')' )?
		//        ('helicopter' '(' helicopter+=[Helicopter|EString] ( "," helicopter+=[Helicopter|EString])* ')' )?
		//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Destroyer}
		//'Destroyer'
		//name=EString
		//'{'
		//    ('amount' amount=EInt)?
		//    ('drone' '(' drone+=[Drone|EString] ( "," drone+=[Drone|EString])* ')' )?
		//    ('helicopter' '(' helicopter+=[Helicopter|EString] ( "," helicopter+=[Helicopter|EString])* ')' )?
		//    ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Destroyer}
		public Action getDestroyerAction_0() { return cDestroyerAction_0; }
		
		//'Destroyer'
		public Keyword getDestroyerKeyword_1() { return cDestroyerKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('amount' amount=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'amount'
		public Keyword getAmountKeyword_4_0() { return cAmountKeyword_4_0; }
		
		//amount=EInt
		public Assignment getAmountAssignment_4_1() { return cAmountAssignment_4_1; }
		
		//EInt
		public RuleCall getAmountEIntParserRuleCall_4_1_0() { return cAmountEIntParserRuleCall_4_1_0; }
		
		//('drone' '(' drone+=[Drone|EString] ( "," drone+=[Drone|EString])* ')' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'drone'
		public Keyword getDroneKeyword_5_0() { return cDroneKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//drone+=[Drone|EString]
		public Assignment getDroneAssignment_5_2() { return cDroneAssignment_5_2; }
		
		//[Drone|EString]
		public CrossReference getDroneDroneCrossReference_5_2_0() { return cDroneDroneCrossReference_5_2_0; }
		
		//EString
		public RuleCall getDroneDroneEStringParserRuleCall_5_2_0_1() { return cDroneDroneEStringParserRuleCall_5_2_0_1; }
		
		//( "," drone+=[Drone|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//drone+=[Drone|EString]
		public Assignment getDroneAssignment_5_3_1() { return cDroneAssignment_5_3_1; }
		
		//[Drone|EString]
		public CrossReference getDroneDroneCrossReference_5_3_1_0() { return cDroneDroneCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getDroneDroneEStringParserRuleCall_5_3_1_0_1() { return cDroneDroneEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('helicopter' '(' helicopter+=[Helicopter|EString] ( "," helicopter+=[Helicopter|EString])* ')' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'helicopter'
		public Keyword getHelicopterKeyword_6_0() { return cHelicopterKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//helicopter+=[Helicopter|EString]
		public Assignment getHelicopterAssignment_6_2() { return cHelicopterAssignment_6_2; }
		
		//[Helicopter|EString]
		public CrossReference getHelicopterHelicopterCrossReference_6_2_0() { return cHelicopterHelicopterCrossReference_6_2_0; }
		
		//EString
		public RuleCall getHelicopterHelicopterEStringParserRuleCall_6_2_0_1() { return cHelicopterHelicopterEStringParserRuleCall_6_2_0_1; }
		
		//( "," helicopter+=[Helicopter|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//helicopter+=[Helicopter|EString]
		public Assignment getHelicopterAssignment_6_3_1() { return cHelicopterAssignment_6_3_1; }
		
		//[Helicopter|EString]
		public CrossReference getHelicopterHelicopterCrossReference_6_3_1_0() { return cHelicopterHelicopterCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getHelicopterHelicopterEStringParserRuleCall_6_3_1_0_1() { return cHelicopterHelicopterEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'ammunitions'
		public Keyword getAmmunitionsKeyword_7_0() { return cAmmunitionsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_7_2() { return cAmmunitionsAssignment_7_2; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_7_2_0() { return cAmmunitionsAmmunitionParserRuleCall_7_2_0; }
		
		//( "," ammunitions+=Ammunition)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_7_3_1() { return cAmmunitionsAssignment_7_3_1; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_7_3_1_0() { return cAmmunitionsAmmunitionParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class AircraftCarrierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.AircraftCarrier");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAircraftCarrierAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAircraftCarrierKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAmountKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAmountAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAmountEIntParserRuleCall_4_1_0 = (RuleCall)cAmountAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDroneKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cDroneAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cDroneDroneCrossReference_5_2_0 = (CrossReference)cDroneAssignment_5_2.eContents().get(0);
		private final RuleCall cDroneDroneEStringParserRuleCall_5_2_0_1 = (RuleCall)cDroneDroneCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cDroneAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cDroneDroneCrossReference_5_3_1_0 = (CrossReference)cDroneAssignment_5_3_1.eContents().get(0);
		private final RuleCall cDroneDroneEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cDroneDroneCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCarrieraircraftKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cCarrieraircraftAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cCarrieraircraftCarrierAircraftCrossReference_6_2_0 = (CrossReference)cCarrieraircraftAssignment_6_2.eContents().get(0);
		private final RuleCall cCarrieraircraftCarrierAircraftEStringParserRuleCall_6_2_0_1 = (RuleCall)cCarrieraircraftCarrierAircraftCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cCarrieraircraftAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cCarrieraircraftCarrierAircraftCrossReference_6_3_1_0 = (CrossReference)cCarrieraircraftAssignment_6_3_1.eContents().get(0);
		private final RuleCall cCarrieraircraftCarrierAircraftEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cCarrieraircraftCarrierAircraftCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAmmunitionsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cAmmunitionsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_7_2_0 = (RuleCall)cAmmunitionsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cAmmunitionsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_7_3_1_0 = (RuleCall)cAmmunitionsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//AircraftCarrier returns AircraftCarrier:
		//    {AircraftCarrier}
		//    'AircraftCarrier'
		//    name=EString
		//    '{'
		//        ('amount' amount=EInt)?
		//        ('drone' '(' drone+=[Drone|EString] ( "," drone+=[Drone|EString])* ')' )?
		//        ('carrieraircraft' '(' carrieraircraft+=[CarrierAircraft|EString] ( "," carrieraircraft+=[CarrierAircraft|EString])* ')' )?
		//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{AircraftCarrier}
		//'AircraftCarrier'
		//name=EString
		//'{'
		//    ('amount' amount=EInt)?
		//    ('drone' '(' drone+=[Drone|EString] ( "," drone+=[Drone|EString])* ')' )?
		//    ('carrieraircraft' '(' carrieraircraft+=[CarrierAircraft|EString] ( "," carrieraircraft+=[CarrierAircraft|EString])* ')' )?
		//    ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{AircraftCarrier}
		public Action getAircraftCarrierAction_0() { return cAircraftCarrierAction_0; }
		
		//'AircraftCarrier'
		public Keyword getAircraftCarrierKeyword_1() { return cAircraftCarrierKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('amount' amount=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'amount'
		public Keyword getAmountKeyword_4_0() { return cAmountKeyword_4_0; }
		
		//amount=EInt
		public Assignment getAmountAssignment_4_1() { return cAmountAssignment_4_1; }
		
		//EInt
		public RuleCall getAmountEIntParserRuleCall_4_1_0() { return cAmountEIntParserRuleCall_4_1_0; }
		
		//('drone' '(' drone+=[Drone|EString] ( "," drone+=[Drone|EString])* ')' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'drone'
		public Keyword getDroneKeyword_5_0() { return cDroneKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//drone+=[Drone|EString]
		public Assignment getDroneAssignment_5_2() { return cDroneAssignment_5_2; }
		
		//[Drone|EString]
		public CrossReference getDroneDroneCrossReference_5_2_0() { return cDroneDroneCrossReference_5_2_0; }
		
		//EString
		public RuleCall getDroneDroneEStringParserRuleCall_5_2_0_1() { return cDroneDroneEStringParserRuleCall_5_2_0_1; }
		
		//( "," drone+=[Drone|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//drone+=[Drone|EString]
		public Assignment getDroneAssignment_5_3_1() { return cDroneAssignment_5_3_1; }
		
		//[Drone|EString]
		public CrossReference getDroneDroneCrossReference_5_3_1_0() { return cDroneDroneCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getDroneDroneEStringParserRuleCall_5_3_1_0_1() { return cDroneDroneEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('carrieraircraft' '(' carrieraircraft+=[CarrierAircraft|EString] ( "," carrieraircraft+=[CarrierAircraft|EString])* ')' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'carrieraircraft'
		public Keyword getCarrieraircraftKeyword_6_0() { return cCarrieraircraftKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//carrieraircraft+=[CarrierAircraft|EString]
		public Assignment getCarrieraircraftAssignment_6_2() { return cCarrieraircraftAssignment_6_2; }
		
		//[CarrierAircraft|EString]
		public CrossReference getCarrieraircraftCarrierAircraftCrossReference_6_2_0() { return cCarrieraircraftCarrierAircraftCrossReference_6_2_0; }
		
		//EString
		public RuleCall getCarrieraircraftCarrierAircraftEStringParserRuleCall_6_2_0_1() { return cCarrieraircraftCarrierAircraftEStringParserRuleCall_6_2_0_1; }
		
		//( "," carrieraircraft+=[CarrierAircraft|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//carrieraircraft+=[CarrierAircraft|EString]
		public Assignment getCarrieraircraftAssignment_6_3_1() { return cCarrieraircraftAssignment_6_3_1; }
		
		//[CarrierAircraft|EString]
		public CrossReference getCarrieraircraftCarrierAircraftCrossReference_6_3_1_0() { return cCarrieraircraftCarrierAircraftCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getCarrieraircraftCarrierAircraftEStringParserRuleCall_6_3_1_0_1() { return cCarrieraircraftCarrierAircraftEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'ammunitions'
		public Keyword getAmmunitionsKeyword_7_0() { return cAmmunitionsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_7_2() { return cAmmunitionsAssignment_7_2; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_7_2_0() { return cAmmunitionsAmmunitionParserRuleCall_7_2_0; }
		
		//( "," ammunitions+=Ammunition)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_7_3_1() { return cAmmunitionsAssignment_7_3_1; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_7_3_1_0() { return cAmmunitionsAmmunitionParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ReconnaissanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Reconnaissance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cReconnaissanceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cReconnaissanceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAmountKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAmountAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAmountEIntParserRuleCall_4_1_0 = (RuleCall)cAmountAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAmmunitionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cAmmunitionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_5_2_0 = (RuleCall)cAmmunitionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cAmmunitionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_5_3_1_0 = (RuleCall)cAmmunitionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Reconnaissance returns Reconnaissance:
		//    {Reconnaissance}
		//    'Reconnaissance'
		//    name=EString
		//    '{'
		//        ('amount' amount=EInt)?
		//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Reconnaissance}
		//'Reconnaissance'
		//name=EString
		//'{'
		//    ('amount' amount=EInt)?
		//    ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Reconnaissance}
		public Action getReconnaissanceAction_0() { return cReconnaissanceAction_0; }
		
		//'Reconnaissance'
		public Keyword getReconnaissanceKeyword_1() { return cReconnaissanceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('amount' amount=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'amount'
		public Keyword getAmountKeyword_4_0() { return cAmountKeyword_4_0; }
		
		//amount=EInt
		public Assignment getAmountAssignment_4_1() { return cAmountAssignment_4_1; }
		
		//EInt
		public RuleCall getAmountEIntParserRuleCall_4_1_0() { return cAmountEIntParserRuleCall_4_1_0; }
		
		//('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ammunitions'
		public Keyword getAmmunitionsKeyword_5_0() { return cAmmunitionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_5_2() { return cAmmunitionsAssignment_5_2; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_5_2_0() { return cAmmunitionsAmmunitionParserRuleCall_5_2_0; }
		
		//( "," ammunitions+=Ammunition)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_5_3_1() { return cAmmunitionsAssignment_5_3_1; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_5_3_1_0() { return cAmmunitionsAmmunitionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class StrikeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Strike");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStrikeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStrikeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAmountKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAmountAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAmountEIntParserRuleCall_4_1_0 = (RuleCall)cAmountAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAmmunitionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cAmmunitionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_5_2_0 = (RuleCall)cAmmunitionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cAmmunitionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_5_3_1_0 = (RuleCall)cAmmunitionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Strike returns Strike:
		//    {Strike}
		//    'Strike'
		//    name=EString
		//    '{'
		//        ('amount' amount=EInt)?
		//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Strike}
		//'Strike'
		//name=EString
		//'{'
		//    ('amount' amount=EInt)?
		//    ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Strike}
		public Action getStrikeAction_0() { return cStrikeAction_0; }
		
		//'Strike'
		public Keyword getStrikeKeyword_1() { return cStrikeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('amount' amount=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'amount'
		public Keyword getAmountKeyword_4_0() { return cAmountKeyword_4_0; }
		
		//amount=EInt
		public Assignment getAmountAssignment_4_1() { return cAmountAssignment_4_1; }
		
		//EInt
		public RuleCall getAmountEIntParserRuleCall_4_1_0() { return cAmountEIntParserRuleCall_4_1_0; }
		
		//('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ammunitions'
		public Keyword getAmmunitionsKeyword_5_0() { return cAmmunitionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_5_2() { return cAmmunitionsAssignment_5_2; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_5_2_0() { return cAmmunitionsAmmunitionParserRuleCall_5_2_0; }
		
		//( "," ammunitions+=Ammunition)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_5_3_1() { return cAmmunitionsAssignment_5_3_1; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_5_3_1_0() { return cAmmunitionsAmmunitionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class TransportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Transport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTransportAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTransportKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAmountKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAmountAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAmountEIntParserRuleCall_4_1_0 = (RuleCall)cAmountAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAmmunitionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cAmmunitionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_5_2_0 = (RuleCall)cAmmunitionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cAmmunitionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_5_3_1_0 = (RuleCall)cAmmunitionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Transport returns Transport:
		//    {Transport}
		//    'Transport'
		//    name=EString
		//    '{'
		//        ('amount' amount=EInt)?
		//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Transport}
		//'Transport'
		//name=EString
		//'{'
		//    ('amount' amount=EInt)?
		//    ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Transport}
		public Action getTransportAction_0() { return cTransportAction_0; }
		
		//'Transport'
		public Keyword getTransportKeyword_1() { return cTransportKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('amount' amount=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'amount'
		public Keyword getAmountKeyword_4_0() { return cAmountKeyword_4_0; }
		
		//amount=EInt
		public Assignment getAmountAssignment_4_1() { return cAmountAssignment_4_1; }
		
		//EInt
		public RuleCall getAmountEIntParserRuleCall_4_1_0() { return cAmountEIntParserRuleCall_4_1_0; }
		
		//('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ammunitions'
		public Keyword getAmmunitionsKeyword_5_0() { return cAmmunitionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_5_2() { return cAmmunitionsAssignment_5_2; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_5_2_0() { return cAmmunitionsAmmunitionParserRuleCall_5_2_0; }
		
		//( "," ammunitions+=Ammunition)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_5_3_1() { return cAmmunitionsAssignment_5_3_1; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_5_3_1_0() { return cAmmunitionsAmmunitionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class FighterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Fighter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFighterAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFighterKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAmountKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAmountAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAmountEIntParserRuleCall_4_1_0 = (RuleCall)cAmountAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAmmunitionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cAmmunitionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_5_2_0 = (RuleCall)cAmmunitionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cAmmunitionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_5_3_1_0 = (RuleCall)cAmmunitionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Fighter returns Fighter:
		//    {Fighter}
		//    'Fighter'
		//    name=EString
		//    '{'
		//        ('amount' amount=EInt)?
		//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Fighter}
		//'Fighter'
		//name=EString
		//'{'
		//    ('amount' amount=EInt)?
		//    ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Fighter}
		public Action getFighterAction_0() { return cFighterAction_0; }
		
		//'Fighter'
		public Keyword getFighterKeyword_1() { return cFighterKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('amount' amount=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'amount'
		public Keyword getAmountKeyword_4_0() { return cAmountKeyword_4_0; }
		
		//amount=EInt
		public Assignment getAmountAssignment_4_1() { return cAmountAssignment_4_1; }
		
		//EInt
		public RuleCall getAmountEIntParserRuleCall_4_1_0() { return cAmountEIntParserRuleCall_4_1_0; }
		
		//('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ammunitions'
		public Keyword getAmmunitionsKeyword_5_0() { return cAmmunitionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_5_2() { return cAmmunitionsAssignment_5_2; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_5_2_0() { return cAmmunitionsAmmunitionParserRuleCall_5_2_0; }
		
		//( "," ammunitions+=Ammunition)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_5_3_1() { return cAmmunitionsAssignment_5_3_1; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_5_3_1_0() { return cAmmunitionsAmmunitionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ReconElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Recon");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cReconAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cReconKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAmountKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAmountAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAmountEIntParserRuleCall_4_1_0 = (RuleCall)cAmountAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAmmunitionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cAmmunitionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_5_2_0 = (RuleCall)cAmmunitionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cAmmunitionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_5_3_1_0 = (RuleCall)cAmmunitionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Recon returns Recon:
		//    {Recon}
		//    'Recon'
		//    name=EString
		//    '{'
		//        ('amount' amount=EInt)?
		//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Recon}
		//'Recon'
		//name=EString
		//'{'
		//    ('amount' amount=EInt)?
		//    ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Recon}
		public Action getReconAction_0() { return cReconAction_0; }
		
		//'Recon'
		public Keyword getReconKeyword_1() { return cReconKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('amount' amount=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'amount'
		public Keyword getAmountKeyword_4_0() { return cAmountKeyword_4_0; }
		
		//amount=EInt
		public Assignment getAmountAssignment_4_1() { return cAmountAssignment_4_1; }
		
		//EInt
		public RuleCall getAmountEIntParserRuleCall_4_1_0() { return cAmountEIntParserRuleCall_4_1_0; }
		
		//('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ammunitions'
		public Keyword getAmmunitionsKeyword_5_0() { return cAmmunitionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_5_2() { return cAmmunitionsAssignment_5_2; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_5_2_0() { return cAmmunitionsAmmunitionParserRuleCall_5_2_0; }
		
		//( "," ammunitions+=Ammunition)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_5_3_1() { return cAmmunitionsAssignment_5_3_1; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_5_3_1_0() { return cAmmunitionsAmmunitionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class HelicopterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Helicopter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cHelicopterAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cHelicopterKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAmountKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAmountAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAmountEIntParserRuleCall_4_1_0 = (RuleCall)cAmountAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAmmunitionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cAmmunitionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_5_2_0 = (RuleCall)cAmmunitionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cAmmunitionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cAmmunitionsAmmunitionParserRuleCall_5_3_1_0 = (RuleCall)cAmmunitionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Helicopter returns Helicopter:
		//    {Helicopter}
		//    'Helicopter'
		//    name=EString
		//    '{'
		//        ('amount' amount=EInt)?
		//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Helicopter}
		//'Helicopter'
		//name=EString
		//'{'
		//    ('amount' amount=EInt)?
		//    ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Helicopter}
		public Action getHelicopterAction_0() { return cHelicopterAction_0; }
		
		//'Helicopter'
		public Keyword getHelicopterKeyword_1() { return cHelicopterKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('amount' amount=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'amount'
		public Keyword getAmountKeyword_4_0() { return cAmountKeyword_4_0; }
		
		//amount=EInt
		public Assignment getAmountAssignment_4_1() { return cAmountAssignment_4_1; }
		
		//EInt
		public RuleCall getAmountEIntParserRuleCall_4_1_0() { return cAmountEIntParserRuleCall_4_1_0; }
		
		//('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ammunitions'
		public Keyword getAmmunitionsKeyword_5_0() { return cAmmunitionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_5_2() { return cAmmunitionsAssignment_5_2; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_5_2_0() { return cAmmunitionsAmmunitionParserRuleCall_5_2_0; }
		
		//( "," ammunitions+=Ammunition)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//ammunitions+=Ammunition
		public Assignment getAmmunitionsAssignment_5_3_1() { return cAmmunitionsAssignment_5_3_1; }
		
		//Ammunition
		public RuleCall getAmmunitionsAmmunitionParserRuleCall_5_3_1_0() { return cAmmunitionsAmmunitionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class MissileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Missile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMissileAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMissileKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAmountKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAmountAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAmountEIntParserRuleCall_4_1_0 = (RuleCall)cAmountAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Missile returns Missile:
		//    {Missile}
		//    'Missile'
		//    name=EString
		//    '{'
		//        ('amount' amount=EInt)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Missile}
		//'Missile'
		//name=EString
		//'{'
		//    ('amount' amount=EInt)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Missile}
		public Action getMissileAction_0() { return cMissileAction_0; }
		
		//'Missile'
		public Keyword getMissileKeyword_1() { return cMissileKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('amount' amount=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'amount'
		public Keyword getAmountKeyword_4_0() { return cAmountKeyword_4_0; }
		
		//amount=EInt
		public Assignment getAmountAssignment_4_1() { return cAmountAssignment_4_1; }
		
		//EInt
		public RuleCall getAmountEIntParserRuleCall_4_1_0() { return cAmountEIntParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ShellElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Shell");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cShellAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cShellKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAmountKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAmountAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAmountEIntParserRuleCall_4_1_0 = (RuleCall)cAmountAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Shell returns Shell:
		//    {Shell}
		//    'Shell'
		//    name=EString
		//    '{'
		//        ('amount' amount=EInt)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Shell}
		//'Shell'
		//name=EString
		//'{'
		//    ('amount' amount=EInt)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Shell}
		public Action getShellAction_0() { return cShellAction_0; }
		
		//'Shell'
		public Keyword getShellKeyword_1() { return cShellKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('amount' amount=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'amount'
		public Keyword getAmountKeyword_4_0() { return cAmountKeyword_4_0; }
		
		//amount=EInt
		public Assignment getAmountAssignment_4_1() { return cAmountAssignment_4_1; }
		
		//EInt
		public RuleCall getAmountEIntParserRuleCall_4_1_0() { return cAmountEIntParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class TorpedoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Torpedo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTorpedoAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTorpedoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAmountKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAmountAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAmountEIntParserRuleCall_4_1_0 = (RuleCall)cAmountAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Torpedo returns Torpedo:
		//    {Torpedo}
		//    'Torpedo'
		//    name=EString
		//    '{'
		//        ('amount' amount=EInt)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Torpedo}
		//'Torpedo'
		//name=EString
		//'{'
		//    ('amount' amount=EInt)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Torpedo}
		public Action getTorpedoAction_0() { return cTorpedoAction_0; }
		
		//'Torpedo'
		public Keyword getTorpedoKeyword_1() { return cTorpedoKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('amount' amount=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'amount'
		public Keyword getAmountKeyword_4_0() { return cAmountKeyword_4_0; }
		
		//amount=EInt
		public Assignment getAmountAssignment_4_1() { return cAmountAssignment_4_1; }
		
		//EInt
		public RuleCall getAmountEIntParserRuleCall_4_1_0() { return cAmountEIntParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	private final ResourcesElements pResources;
	private final VehicleElements pVehicle;
	private final AmmunitionElements pAmmunition;
	private final DroneElements pDrone;
	private final CarrierAircraftElements pCarrierAircraft;
	private final EStringElements pEString;
	private final EIntElements pEInt;
	private final FrigateElements pFrigate;
	private final DestroyerElements pDestroyer;
	private final AircraftCarrierElements pAircraftCarrier;
	private final ReconnaissanceElements pReconnaissance;
	private final StrikeElements pStrike;
	private final TransportElements pTransport;
	private final FighterElements pFighter;
	private final ReconElements pRecon;
	private final HelicopterElements pHelicopter;
	private final MissileElements pMissile;
	private final ShellElements pShell;
	private final TorpedoElements pTorpedo;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pResources = new ResourcesElements();
		this.pVehicle = new VehicleElements();
		this.pAmmunition = new AmmunitionElements();
		this.pDrone = new DroneElements();
		this.pCarrierAircraft = new CarrierAircraftElements();
		this.pEString = new EStringElements();
		this.pEInt = new EIntElements();
		this.pFrigate = new FrigateElements();
		this.pDestroyer = new DestroyerElements();
		this.pAircraftCarrier = new AircraftCarrierElements();
		this.pReconnaissance = new ReconnaissanceElements();
		this.pStrike = new StrikeElements();
		this.pTransport = new TransportElements();
		this.pFighter = new FighterElements();
		this.pRecon = new ReconElements();
		this.pHelicopter = new HelicopterElements();
		this.pMissile = new MissileElements();
		this.pShell = new ShellElements();
		this.pTorpedo = new TorpedoElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Resources returns Resources:
	//    {Resources}
	//    'Resources'
	//    name=EString
	//    '{'
	//        ('vehicles' '{' vehicles+=Vehicle ( "," vehicles+=Vehicle)* '}' )?
	//    '}';
	public ResourcesElements getResourcesAccess() {
		return pResources;
	}
	
	public ParserRule getResourcesRule() {
		return getResourcesAccess().getRule();
	}
	
	//Vehicle returns Vehicle:
	//    Frigate | Destroyer | AircraftCarrier | Reconnaissance | Strike | Transport | Fighter | Recon | Helicopter;
	public VehicleElements getVehicleAccess() {
		return pVehicle;
	}
	
	public ParserRule getVehicleRule() {
		return getVehicleAccess().getRule();
	}
	
	//Ammunition returns Ammunition:
	//    Missile | Shell | Torpedo;
	public AmmunitionElements getAmmunitionAccess() {
		return pAmmunition;
	}
	
	public ParserRule getAmmunitionRule() {
		return getAmmunitionAccess().getRule();
	}
	
	//Drone returns Drone:
	//    Reconnaissance | Strike | Transport;
	public DroneElements getDroneAccess() {
		return pDrone;
	}
	
	public ParserRule getDroneRule() {
		return getDroneAccess().getRule();
	}
	
	//CarrierAircraft returns CarrierAircraft:
	//    Fighter | Recon | Helicopter;
	public CarrierAircraftElements getCarrierAircraftAccess() {
		return pCarrierAircraft;
	}
	
	public ParserRule getCarrierAircraftRule() {
		return getCarrierAircraftAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Frigate returns Frigate:
	//    {Frigate}
	//    'Frigate'
	//    name=EString
	//    '{'
	//        ('amount' amount=EInt)?
	//        ('drone' '(' drone+=[Drone|EString] ( "," drone+=[Drone|EString])* ')' )?
	//        ('helicopter' '(' helicopter+=[Helicopter|EString] ( "," helicopter+=[Helicopter|EString])* ')' )?
	//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
	//    '}';
	public FrigateElements getFrigateAccess() {
		return pFrigate;
	}
	
	public ParserRule getFrigateRule() {
		return getFrigateAccess().getRule();
	}
	
	//Destroyer returns Destroyer:
	//    {Destroyer}
	//    'Destroyer'
	//    name=EString
	//    '{'
	//        ('amount' amount=EInt)?
	//        ('drone' '(' drone+=[Drone|EString] ( "," drone+=[Drone|EString])* ')' )?
	//        ('helicopter' '(' helicopter+=[Helicopter|EString] ( "," helicopter+=[Helicopter|EString])* ')' )?
	//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
	//    '}';
	public DestroyerElements getDestroyerAccess() {
		return pDestroyer;
	}
	
	public ParserRule getDestroyerRule() {
		return getDestroyerAccess().getRule();
	}
	
	//AircraftCarrier returns AircraftCarrier:
	//    {AircraftCarrier}
	//    'AircraftCarrier'
	//    name=EString
	//    '{'
	//        ('amount' amount=EInt)?
	//        ('drone' '(' drone+=[Drone|EString] ( "," drone+=[Drone|EString])* ')' )?
	//        ('carrieraircraft' '(' carrieraircraft+=[CarrierAircraft|EString] ( "," carrieraircraft+=[CarrierAircraft|EString])* ')' )?
	//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
	//    '}';
	public AircraftCarrierElements getAircraftCarrierAccess() {
		return pAircraftCarrier;
	}
	
	public ParserRule getAircraftCarrierRule() {
		return getAircraftCarrierAccess().getRule();
	}
	
	//Reconnaissance returns Reconnaissance:
	//    {Reconnaissance}
	//    'Reconnaissance'
	//    name=EString
	//    '{'
	//        ('amount' amount=EInt)?
	//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
	//    '}';
	public ReconnaissanceElements getReconnaissanceAccess() {
		return pReconnaissance;
	}
	
	public ParserRule getReconnaissanceRule() {
		return getReconnaissanceAccess().getRule();
	}
	
	//Strike returns Strike:
	//    {Strike}
	//    'Strike'
	//    name=EString
	//    '{'
	//        ('amount' amount=EInt)?
	//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
	//    '}';
	public StrikeElements getStrikeAccess() {
		return pStrike;
	}
	
	public ParserRule getStrikeRule() {
		return getStrikeAccess().getRule();
	}
	
	//Transport returns Transport:
	//    {Transport}
	//    'Transport'
	//    name=EString
	//    '{'
	//        ('amount' amount=EInt)?
	//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
	//    '}';
	public TransportElements getTransportAccess() {
		return pTransport;
	}
	
	public ParserRule getTransportRule() {
		return getTransportAccess().getRule();
	}
	
	//Fighter returns Fighter:
	//    {Fighter}
	//    'Fighter'
	//    name=EString
	//    '{'
	//        ('amount' amount=EInt)?
	//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
	//    '}';
	public FighterElements getFighterAccess() {
		return pFighter;
	}
	
	public ParserRule getFighterRule() {
		return getFighterAccess().getRule();
	}
	
	//Recon returns Recon:
	//    {Recon}
	//    'Recon'
	//    name=EString
	//    '{'
	//        ('amount' amount=EInt)?
	//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
	//    '}';
	public ReconElements getReconAccess() {
		return pRecon;
	}
	
	public ParserRule getReconRule() {
		return getReconAccess().getRule();
	}
	
	//Helicopter returns Helicopter:
	//    {Helicopter}
	//    'Helicopter'
	//    name=EString
	//    '{'
	//        ('amount' amount=EInt)?
	//        ('ammunitions' '{' ammunitions+=Ammunition ( "," ammunitions+=Ammunition)* '}' )?
	//    '}';
	public HelicopterElements getHelicopterAccess() {
		return pHelicopter;
	}
	
	public ParserRule getHelicopterRule() {
		return getHelicopterAccess().getRule();
	}
	
	//Missile returns Missile:
	//    {Missile}
	//    'Missile'
	//    name=EString
	//    '{'
	//        ('amount' amount=EInt)?
	//    '}';
	public MissileElements getMissileAccess() {
		return pMissile;
	}
	
	public ParserRule getMissileRule() {
		return getMissileAccess().getRule();
	}
	
	//Shell returns Shell:
	//    {Shell}
	//    'Shell'
	//    name=EString
	//    '{'
	//        ('amount' amount=EInt)?
	//    '}';
	public ShellElements getShellAccess() {
		return pShell;
	}
	
	public ParserRule getShellRule() {
		return getShellAccess().getRule();
	}
	
	//Torpedo returns Torpedo:
	//    {Torpedo}
	//    'Torpedo'
	//    name=EString
	//    '{'
	//        ('amount' amount=EInt)?
	//    '}';
	public TorpedoElements getTorpedoAccess() {
		return pTorpedo;
	}
	
	public ParserRule getTorpedoRule() {
		return getTorpedoAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
